baseURL = 'https://thecybercafeman.github.io/cafeblog/'
languageCode = 'es-ES'
defaultContentLanguage = "es"
title = 'Cafeteria Y Blog Cibernetico'
theme = 'Monochrome'

[caches]
 [caches.images]
 dir = ':cacheDir/Images'	
